/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#38485d",
        "on-primary-container": "#cad3ff",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary": "#ffffff",
        secondary: "#505f76",
        tertiary: "#004f35",
        "on-tertiary-fixed-variant": "#005236",
        "on-background": "#1a1b23",
        "on-error": "#ffffff",
        "inverse-primary": "#b7c4ff",
        "error-container": "#ffdad6",
        "surface-container-high": "#e8e7f3",
        "outline-variant": "#c4c5d7",
        "on-surface-variant": "#434655",
        "primary-container": "#1d4ed8",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed": "#6ffbbe",
        "inverse-on-surface": "#f0f0fb",
        "primary-fixed-dim": "#b7c4ff",
        "surface-bright": "#faf8ff",
        "on-tertiary-container": "#60eeb1",
        surface: "#faf8ff",
        "secondary-fixed-dim": "#b7c8e1",
        "inverse-surface": "#2e3039",
        "on-secondary-container": "#54647a",
        "surface-variant": "#e2e1ed",
        "surface-container": "#ededf9",
        error: "#ba1a1a",
        "primary-fixed": "#dce1ff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1a1b23",
        "surface-dim": "#d9d9e5",
        "on-primary": "#ffffff",
        "surface-tint": "#2151da",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001551",
        "tertiary-container": "#006a48",
        primary: "#0037b0",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d3e4fe",
        "surface-container-highest": "#e2e1ed",
        background: "#faf8ff",
        outline: "#747686",
        "surface-container-low": "#f3f2fe",
        "secondary-container": "#d0e1fb",
        "on-primary-fixed-variant": "#0039b5",
        "on-tertiary-fixed": "#002113",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        xl: "32px",
        lg: "24px",
        margin: "32px",
        "2xl": "48px",
        md: "16px",
        base: "8px",
        sm: "12px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        h1: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.2", fontWeight: "500" }],
        h3: ["24px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        h2: ["30px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
